/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifba.dashboard.froteira;

import br.edu.ifba.dashboard.constantes.Constantes;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaConfiguracoes extends javax.swing.JDialog {

    /**
     * Creates new form Configuracoes
     */
    public TelaConfiguracoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.telaPrincipal = (TelaPrincipal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoUf = new javax.swing.JTextField();
        limparUf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        limparCidade = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoPessoa = new javax.swing.JTextField();
        limparPessoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoDesaparecimento = new javax.swing.JTextField();
        limparDesaparecimento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        padraoSegundos = new javax.swing.JButton();
        campoSegundos = new javax.swing.JSpinner();
        botaoEditar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Configurações de serviços");

        jLabel2.setText("EndPoint de Ufs:");

        campoUf.setEnabled(false);

        limparUf.setText("Limpar");
        limparUf.setEnabled(false);
        limparUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparUfActionPerformed(evt);
            }
        });

        jLabel3.setText("EndPoint de Cidades:");

        campoCidade.setEnabled(false);

        limparCidade.setText("Limpar");
        limparCidade.setEnabled(false);
        limparCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("EndPoint de Pessoas:");

        campoPessoa.setEnabled(false);

        limparPessoa.setText("Limpar");
        limparPessoa.setEnabled(false);
        limparPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparPessoaActionPerformed(evt);
            }
        });

        jLabel5.setText("EndPoint de Desaparecimentos:");

        campoDesaparecimento.setEnabled(false);

        limparDesaparecimento.setText("Limpar");
        limparDesaparecimento.setEnabled(false);
        limparDesaparecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDesaparecimentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Configurações gerais");

        jLabel7.setText("Tempo de atualização (>=1) em segundos:");

        padraoSegundos.setText("Padrão");
        padraoSegundos.setEnabled(false);
        padraoSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padraoSegundosActionPerformed(evt);
            }
        });

        campoSegundos.setEnabled(false);

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar e fechar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSalvar))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparUf))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparCidade))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparPessoa))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoDesaparecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparDesaparecimento))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(campoSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(padraoSegundos))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparUf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDesaparecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparDesaparecimento))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(padraoSegundos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditar)
                    .addComponent(botaoSalvar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limparUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparUfActionPerformed
        campoUf.setText("");
    }//GEN-LAST:event_limparUfActionPerformed

    private void limparCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCidadeActionPerformed
        campoCidade.setText("");
    }//GEN-LAST:event_limparCidadeActionPerformed

    private void limparPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparPessoaActionPerformed
        campoPessoa.setText("");
    }//GEN-LAST:event_limparPessoaActionPerformed

    private void limparDesaparecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDesaparecimentoActionPerformed
        campoDesaparecimento.setText("");
    }//GEN-LAST:event_limparDesaparecimentoActionPerformed

    private void padraoSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padraoSegundosActionPerformed
        campoSegundos.setValue(5);
    }//GEN-LAST:event_padraoSegundosActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        if(botaoEditar.getText().equals("Cancelar")){
            setarValores();
            this.dispose();
        }
        configurarCampos(botaoEditar.getText().equals("Editar"));
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (verificarCampos()) {
            telaPrincipal.salvarConfigs(campoUf.getText(),
                    campoCidade.getText(),
                    campoPessoa.getText(),
                    campoDesaparecimento.getText(),
                    String.valueOf(campoSegundos.getValue()));
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConfiguracoes dialog = new TelaConfiguracoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoDesaparecimento;
    private javax.swing.JTextField campoPessoa;
    private javax.swing.JSpinner campoSegundos;
    private javax.swing.JTextField campoUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton limparCidade;
    private javax.swing.JButton limparDesaparecimento;
    private javax.swing.JButton limparPessoa;
    private javax.swing.JButton limparUf;
    private javax.swing.JButton padraoSegundos;
    // End of variables declaration//GEN-END:variables
    TelaPrincipal telaPrincipal;

    private void configurarCampos(boolean b) {
        campoUf.setEnabled(b);
        campoCidade.setEnabled(b);
        campoPessoa.setEnabled(b);
        campoDesaparecimento.setEnabled(b);
        campoSegundos.setEnabled(b);
        limparUf.setEnabled(b);
        limparCidade.setEnabled(b);
        limparPessoa.setEnabled(b);
        limparDesaparecimento.setEnabled(b);
        padraoSegundos.setEnabled(b);
        botaoSalvar.setEnabled(b);

        botaoEditar.setText(b ? "Cancelar" : "Editar");
    }

    private boolean verificarCampos() {
        if (campoUf.getText().isBlank() || campoUf.getText().isEmpty()) {
            return false;
        }
        if (campoCidade.getText().isBlank() || campoCidade.getText().isEmpty()) {
            return false;
        }
        if (campoPessoa.getText().isBlank() || campoPessoa.getText().isEmpty()) {
            return false;
        }
        if (campoDesaparecimento.getText().isBlank() || campoDesaparecimento.getText().isEmpty()) {
            return false;
        }
        return ((Integer) campoSegundos.getValue()) > 0;
    }

    public void setarValores() {
        campoUf.setText(Constantes.URL_SERVIDOR_GRAPHQL_UFS);
        campoCidade.setText(Constantes.URL_SERVIDOR_GRAPHQL_CIDADES);
        campoPessoa.setText(Constantes.URL_SERVIDOR_GRAPHQL_PESSOAS);
        campoDesaparecimento.setText(Constantes.URL_SERVIDOR_GRAPHQL_DESAPARECIMENTOS);
        campoSegundos.setValue(Constantes.SLEEP/1000);
    }
}
